<template>
    <div>
        <b-container>
            <br>
            <br>
            <b-row>
                <b-col>
                    <h3>
                        Sponsors
                    </h3>
                </b-col>
            </b-row>
            <br>
            <br>
        </b-container>
    </div>
</template>